core/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dreamcatcher.urls', namespace='dreamcatcher')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dreamcatcher/urls.py
from django.urls import path

from . import views

app_name = 'dreamcatcher'

urlpatterns = [
    path('', views.login_page, name='login_page'),
    path('rating', views.rating, name='rating'),
    path('login_view', views.login_view, name='login_view'),
    path('login_register_view', views.login_register_view, name='login_register_view'),
    path('login_register', views.login_register, name='login_register'),
    path('descriere_categorie', views.descriere_categorie, name='descriere_categorie'),
    path('statistici', views.statistici_view, name='statistici_view'),
    path('statistici_stres', views.statistici_view_stres, name='statistici_view_stres'),
    path('statistici_energie', views.statistici_view_energie, name='statistici_view_energie'),
    path('statistici_durata', views.statistici_view_durata, name='statistici_view_durata'),
    path('back', views.back_to_statistici_view, name='back_to_statistici_view'),

]

dreamcatcher/models.py
from django.db import models


# Create your models here.
class User(models.Model):
    username = models.CharField(max_length=255, db_index=True)


class Dream(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.CharField(max_length=255, db_index=True)
    descriere = models.TextField(blank=True)
    eticheta = models.CharField(max_length=255, db_index=True)
    stres = models.DecimalField(max_digits=3, decimal_places=0)
    nivelEnergie = models.DecimalField(max_digits=1, decimal_places=0)
    durata = models.DecimalField(max_digits=1, decimal_places=0)
    data = models.DateTimeField
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

dreamcatcher/forms.py
from django import forms


class UserForm(forms.Form):
    username = forms.CharField(max_length=100, required=True)
    password = forms.CharField(max_length=100, required=True, widget=forms.PasswordInput)
    firstname = forms.CharField(max_length=100, required=True)
    lastname = forms.CharField(max_length=100, required=True)

dreamcatcher/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

from .charts import StressChartCreator, EnergyChartCreator, DurationChartCreator
from .forms import UserForm
from .models import Dream
from django.contrib import messages
from django.db.models.functions import TruncDate
from django.db.models import Avg


def login_page(request):
    return render(request, 'login.html')


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return descriere_categorie(request)
    return render(request, 'login.html')


def login_register(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            firstname = form.cleaned_data.get('firstname')
            lastname = form.cleaned_data.get('lastname')
            user = authenticate(username=username, password=password)
            if user is None:
                user = User.objects.create_user(username=username, password=password, first_name=firstname,
                                                last_name=lastname)
                user.save()
                return render(request, 'success_register.html')
    else:
        form = UserForm()
    return render(request, 'login.html', {'form': form})


def login_register_view(request):
    return render(request, 'register.html')


def descriere_categorie(request):
    return render(request, 'descriere_categorie.html')


def rating(request):
    if request.method == 'POST':
        description = request.POST['description']
        category = request.POST['category']
        user = request.user.username
        dream = Dream(user=user, descriere=description, eticheta=category, stres=0, nivelEnergie=0, durata=0)
        dream.save()
    return render(request, 'rating.html')


@login_required
def statistici_view(request):
    if request.method == 'POST':
        duration = request.POST['duration']
        energy = request.POST['energy']
        stress = request.POST['stress']
        user = request.user.username

        dream = Dream.objects.latest('id')
        dream.durata = duration
        dream.nivelEnergie = energy
        dream.stres = stress
        dream.save()
    return render(request, 'statistici.html')


def back_to_statistici_view(request):
    return render(request, 'statistici.html')


def statistici_view_stres(request):
    chart_creator = StressChartCreator()
    return chart_creator.create_chart(request)


def statistici_view_energie(request):
    chart_creator = EnergyChartCreator()
    return chart_creator.create_chart(request)


def statistici_view_durata(request):
    chart_creator = DurationChartCreator()
    return chart_creator.create_chart(request)

dreamcatcher/templates/base.html
<!DOCTYPE html>

    <meta charset="utf-8" />
    <title>{% block title %}Dreamcatcher{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"
        integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous">
    </script>
 <style>
        body {
            background-color: #89CFF0;
        }

 </style>

<body>
    <header>
    <div id="content">{% block content %} {% endblock %}</div>
    </header>
</body>

dreamcatcher/templates/descriere_categorie.html
{% extends "./base.html" %}
{% load static %}
{% block title %}Descriere somn{% endblock %}
{% block content %}

<section class="py-5 text-center container">
  <div class="row py-lg-5">
    <div class="col-lg-6 col-md-8 mx-auto">
      <h1 class="h1 fw-bold">
        <span style="color: red;">D</span><span style="color: white;">REAM</span><span style="color: red;">C</span><span style="color: white;">ATCHER</span>
      </h1>
      <p class="lead text-muted">Adauga o scurta descriere visului tau si alege categoria relevanta!</p>

      <form method="post" id="myForm3" action="{% url 'dreamcatcher:rating' %}" >
      {% csrf_token %}
      {{ form.as_p }}
        <div class="form-group">
          <h3 class="fw-bold"><span style="color: red;">Description</span></h3>
          <input type="text" class="form-control" id="description" name="description" required>

           <h3 class="fw-bold"><span style="color: red;">Category</span></h3>
            <select class="form-control" name="category" id="category" required>
            <option value="">Choose a category</option>
             <option value="lucide">Vise lucide</option>
             <option value="cosmar">Cosmaruri</option>
             <option value="recurente">Vise recurente</option>
             <option value="vindecare">Visele de vindecare</option>
             <option value="profetice">Visele profetice</option>
             <option value="epice">Visele epice</option>
            </select>

        </div>
        <button class="btn btn-primary my-2" style="background-color: red;" type="submit" id="next" >Next</button>
      </form>
      <a href="{% url 'dreamcatcher:back_to_statistici_view' %}" class="btn btn-primary my-2" style="background-color: green;">Vizualizare statistici</a>

    </div>
  </div>
</section>

{% endblock %}

dreamcatcher/templates/durata_chart.html
{% extends "./base.html" %}

{% load static %}
{% block title %}Period Chart{% endblock %}
{% block content %}

<div class="chart-container">
    <canvas id="myChart3"></canvas>
</div>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script>
    var ctx = document.getElementById('myChart3').getContext('2d');
    var chartData = {{ chart_data|safe }};
    var chart = new Chart(ctx, {
        type: 'line',
        data: chartData,
        options: {
            scales: {
                yAxes: [{
                    ticks: {
                        beginAtZero: true,
                        stepSize: 1,
                        max: 5,
                        fontColor: 'black'
                    }
                }],
                xAxes: [{
                    ticks: {
                        fontColor: 'black'
                    }
                }]
            }
        }
    });
</script>

<a href="{% url 'dreamcatcher:back_to_statistici_view' %}" class="btn btn-primary my-2" style="background-color: green;">Revenire</a>
<style>
  .btn {
    display: block;
    margin: 0 auto;
  }
</style>

<style>
    .chart-container {
        display: flex;
        justify-content: center;
        align-items: center;
        height: 80vh;
    }

    canvas {
        max-width: 100%;
        max-height: 100%;
    }
</style>
{% endblock %}

dreamcatcher/templates/energy_chart.html
{% extends "./base.html" %}

{% load static %}
{% block title %}Energy Chart{% endblock %}
{% block content %}

<div class="chart-container">
    <canvas id="myChart2"></canvas>
</div>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script>
    var ctx = document.getElementById('myChart2').getContext('2d');
    var chartData = {{ chart_data|safe }};
    var chart = new Chart(ctx, {
        type: 'line',
        data: chartData,
        options: {
            scales: {
                yAxes: [{
                    ticks: {
                        beginAtZero: true,
                        stepSize: 1,
                        max: 5,
                        fontColor: 'black'
                    }
                }],
                xAxes: [{
                    ticks: {
                        fontColor: 'black'
                    }
                }]
            }
        }
    });
</script>

<a href="{% url 'dreamcatcher:back_to_statistici_view' %}" class="btn btn-primary my-2" style="background-color: green;">Revenire</a>
<style>
  .btn {
    display: block;
    margin: 0 auto;
  }
</style>

<style>
    .chart-container {
        display: flex;
        justify-content: center;
        align-items: center;
        height: 80vh;
    }

    canvas {
        max-width: 100%;
        max-height: 100%;
    }
</style>
{% endblock %}

dreamcatcher/templates/login.html
{% extends "./base.html" %}

{% load static %}
{% block title %}Sign in{% endblock %}

{% block content %}
<section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
       <h1 class="h1 fw-bold"><span style="color: red;">D</span><span style="color: white;">REAM</span><span style="color: red;">C</span><span style="color: white;">ATCHER</span></h1>
        <p class="lead text-muted" style="color: white;">Introduceti username-ul si parola pentru a incepe monitorizarea viselor! </p>

          <form method="post" id="myForm" action="{% url 'dreamcatcher:login_view' %}" >
             {% csrf_token %}
             {{ form.as_p }}

            <label for="username"><span style="color: red; font-size: 22px;">Username</span></label>
            <input type="text" class="form-control" name="username" id="username" placeholder="Username">

            <label for="username"><span style="color: red; font-size: 22px;">Password</span></label>
            <input type="text" class="form-control" name="password" id="password" placeholder="Password">

            <button class="btn btn-primary my-2" style="background-color: red;" type="submit" id="signin" >Sign in</button>
          </form>

         <a href="{% url 'dreamcatcher:login_register_view' %}" class="btn btn-primary my-2" style="background-color: red;">Create account</a>

      </div>
    </div>
</section>
{% endblock %}

dreamcatcher/templates/rating.html
{% extends "./base.html" %}

{% load static %}

{% block title %}Evaluare somn{% endblock %}

{% block content %}

<section class="py-5 text-center container">
  <div class="row py-lg-5">
    <div class="col-lg-6 col-md-8 mx-auto">
      <h1 class="h1 fw-bold">
        <span style="color: red;">D</span><span style="color: white;">REAM</span><span style="color: red;">C</span><span style="color: white;">ATCHER</span>
      </h1>
      <p class="lead text-muted">Evalueaza calitatea somnului tau</p>

     <form method="POST" id="myForm5" action="{% url 'dreamcatcher:statistici_view' %}" >
       {% csrf_token %}
       {{ form.as_p }}

    <h3 class="fw-bold">
    <span style="color: red;">Durata</span></h3>
    <div class="star-rating">

    <input type="radio" name="duration" value="1"><i></i>
    <input type="radio" name="duration" value="2"><i></i>
    <input type="radio" name="duration" value="3"><i></i>
    <input type="radio" name="duration" value="4"><i></i>
    <input type="radio" name="duration" value="5"><i></i>
    </div>

   <h3 class="fw-bold"><span style="color: red;">Nivel de energie</span></h3>
   <div class="star-rating">

    <input type="radio" name="energy" value="1"><i></i>
    <input type="radio" name="energy" value="2"><i></i>
    <input type="radio" name="energy" value="3"><i></i>
    <input type="radio" name="energy" value="4"><i></i>
    <input type="radio" name="energy" value="5"><i></i>
   </div>

   <h3 class="fw-bold"><span style="color: red;">Stres</span></h3>
   <div class="star-rating">

    <input type="radio" name="stress" value="1"><i></i>
    <input type="radio" name="stress" value="2"><i></i>
    <input type="radio" name="stress" value="3"><i></i>
    <input type="radio" name="stress" value="4"><i></i>
    <input type="radio" name="stress" value="5"><i></i>
   </div>
   <br>
   <button type="submit" class="btn btn-primary my-2" style="background-color: red;">Evalueaza</button>
   </form>
   </div>
  </div>
</section>
{% endblock %}

dreamcatcher/templates/register.html
{% extends "./base.html" %}

{% load static %}
{% block title %}Sign in{% endblock %}

{% block content %}
<section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
       <h1 class="h1 fw-bold"><span style="color: red;">D</span><span style="color: white;">REAM</span><span style="color: red;">C</span><span style="color: white;">ATCHER</span></h1>
        <p class="lead text-muted" style="color: white;">Creaza un cont pentru a incepe monitorizarea viselor! </p>

          <form method="post" id="myForm2" action="{% url 'dreamcatcher:login_register' %}" >
             {% csrf_token %}
             {{ form.as_p }}

            <label for="username"><span style="color: red; font-size: 22px;">Username</span></label>
            <input type="text" class="form-control" name="username" id="username" placeholder="Username" required>

            <label for="username"><span style="color: red; font-size: 22px;">Password</span></label>
            <input type="text" class="form-control" name="password" id="password" placeholder="Password" required>

            <label for="firstname"><span style="color: red; font-size: 22px;">First Name</span></label>
            <input type="text" class="form-control" name="firstname" id="firstname" placeholder="First name" required>

            <label for="lastname"><span style="color: red; font-size: 22px;">Last Name</span></label>
            <input type="text" class="form-control" name="lastname" id="lastname" placeholder="Last Name" required>

            <button class="btn btn-primary my-2" style="background-color: red;" type="submit" id="createaccount" >Create account</button>

          </form>
          <a href="{% url 'dreamcatcher:login_page' %}" class="btn btn-primary my-2" style="background-color: red;">Return to Sign In Page</a>


      </div>
    </div>
</section>
{% endblock %}

dreamcatcher/templates/statistici.html
{% extends "./base.html" %}

{% load static %}
{% block title %}Charts{% endblock %}

{% block content %}
<section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
       <h1 class="h1 fw-bold"><span style="color: red;">D</span><span style="color: white;">REAM</span><span style="color: red;">C</span><span style="color: white;">ATCHER</span></h1>
        <p class="lead text-muted" style="color: white;">Vizualizati statisticile! </p>

         <a href="{% url 'dreamcatcher:statistici_view_stres' %}" class="btn btn-primary my-2" style="background-color: red;">Statistici dupa nivelul de stres</a>
         <a href="{% url 'dreamcatcher:statistici_view_energie' %}" class="btn btn-primary my-2" style="background-color: red;">Statistici dupa nivelul de energie</a>
         <a href="{% url 'dreamcatcher:statistici_view_durata' %}" class="btn btn-primary my-2" style="background-color: red;">Statistici dupa durata somnului</a>
         <a href="{% url 'dreamcatcher:descriere_categorie' %}" class="btn btn-primary my-2" style="background-color: green;">Revenire la pagina principala</a>

      </div>
    </div>
</section>
{% endblock %}

dreamcatcher/templates/stres_chart.html
{% extends "./base.html" %}

{% load static %}
{% block title %}Stress Chart{% endblock %}
{% block content %}

<div class="chart-container">
    <canvas id="myChart"></canvas>
</div>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script>
    var ctx = document.getElementById('myChart').getContext('2d');
    var chartData = {{ chart_data|safe }};
    var chart = new Chart(ctx, {
        type: 'line',
        data: chartData,
        options: {
            scales: {
                yAxes: [{
                    ticks: {
                        beginAtZero: true,
                        stepSize: 1,
                        max: 5,
                        fontColor: 'black'
                    }
                }],
                xAxes: [{
                    ticks: {
                        fontColor: 'black'
                    }
                }]
            }
        }
    });
</script>

<a href="{% url 'dreamcatcher:back_to_statistici_view' %}" class="btn btn-primary my-2" style="background-color: green;">Revenire</a>
<style>
  .btn {
    display: block;
    margin: 0 auto;
  }
</style>

<style>
    .chart-container {
        display: flex;
        justify-content: center;
        align-items: center;
        height: 80vh;
    }

    canvas {
        max-width: 100%;
        max-height: 100%;
    }
</style>
{% endblock %}

dreamcatcher/templates/success_register.html
{% extends "./base.html" %}

{% load static %}
{% block title %}Sign in{% endblock %}

{% block content %}
<section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
       <h1 class="h1 fw-bold"><span style="color: red;">D</span><span style="color: white;">REAM</span><span style="color: red;">C</span><span style="color: white;">ATCHER</span></h1>
        <p class="lead text-muted" style="color: white; font-size: 30px;">Contul a fost creat cu succes! </p>

          <a href="{% url 'dreamcatcher:login_page' %}" class="btn btn-primary my-2" style="background-color: red;">Return to Sign In Page</a>

      </div>
    </div>
</section>
{% endblock %}